version: '2.0'

services:
    app01:
        shm_size: '1000000000'
        build:
            context: ./flask
        tty: true
    app02:
        shm_size: '1000000000'
        build:
            context: ./flask
        tty: true
    nginx:
        build: ./nginx
        tty: true
        links:
            - app01
            - app02
        ports:
            - '80:80'